// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARjuJdV3v44JQght_cLiWGFplPL6YnbjM',
    appId: '1:597907003188:web:7f476895b0cebae4a4f761',
    messagingSenderId: '597907003188',
    projectId: 'w4-25-rapeephat',
    authDomain: 'w4-25-rapeephat.firebaseapp.com',
    storageBucket: 'w4-25-rapeephat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXlngVHcbAfWwHiq-L2-CHBHqQcxUVed0',
    appId: '1:597907003188:android:1dba7414eb39728fa4f761',
    messagingSenderId: '597907003188',
    projectId: 'w4-25-rapeephat',
    storageBucket: 'w4-25-rapeephat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoOEnLmpNMuofhovEPpe774HJu0pLgPeg',
    appId: '1:597907003188:ios:eb58d26e76bc41b1a4f761',
    messagingSenderId: '597907003188',
    projectId: 'w4-25-rapeephat',
    storageBucket: 'w4-25-rapeephat.firebasestorage.app',
    iosBundleId: 'com.example.w425Rapeephat',
  );
}
